/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rqyziyfdujrnrvenmqha"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxeXppeWZkdWpybnJ2ZW5tcWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMDM4ODMsImV4cCI6MjA3NjU3OTg4M30.1TjPpjUzRYcXxe-tXHdN-iIQeGoSZBdnlH4nOl6ORDY"